services:
 portainer:
 image: portainer/portainer-ce:latest
 container_name: wp_portainer
 ports:
 - "9443:9443"
 volumes:
# Docker 소켓 연결
 - /var/run/docker.sock:/var/run/docker.sock
 - portainer_data:/data # 설정 영구 저장
 networks:
 - wp_net
 restart: unless-stopped
volumes:
 portainer_data:
networks:
 wp_net:
 external: true # 10주차 네트워크 재사용
name: wordpress_wp_net
# 9443 : HTTPS (자체 인증서 내장, 별도 설정 X)
